language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"
services:
  - postgresql
env:
  global:
  - NODE_ENV=test
addons:
    code_climate:
        repo_token:
          secure: "xzA8nj38HweOO12G1w7EG/dfmFrnopUeOWJY4G0QF9FXURwdcX848YM1RMW08RH4m3M4As+dIAIRFDILkv8MQ4PPBBc/UjSHU8rUvOM9UUTDS2n696IbLekBVE6yHUMRgMC0e1MynXqPh+KCVD6CqVbNEndBafDj08Dxej5h8uOnUX93PQlLOvTGE/vrqTSouGbgEzo9Xn0L8bfFWtkLyUJBC7qY6chZfH4UR58sphFQVazkp8YdS3PCL3h6WA8Q6tfXG56EN76gRIGxZbVCQvVwHCUf60KkIepNXg8WE0d/aqTKarZYr8axvARTAiXkdGO+g4rNWz1A+GOxWSnQW4HFxzjG501VJcSkwDEVCh2He5xWHlIiczEWaa0QwVvVzvLBdLCN11jmf0VmtX0d7wedrZ0qK0552B6jl+kvz279pqyThnIyCeHDnSN3IYLmXKBt6TOfVsX+j+8Cu3gtxESqMyvq5e3Onxq/8g/4Qcyl+Ri0ruqnlgRPqDHobzgLRCrjELgrhfXTBpgRIQrK1Tdkkm6I22iVhFPwfNmmN9e8sgGzTzuM/wfZxycCelM3D29m4hUnpna5yPexnrdNIhe9Xq0WGTnTBuQmEL58tIMotb/InYScjZxniqxU0Z24IUOmsqEJglleduUqO/so8kM6/tIkzJGbFsaIS76XVXA="
script:
  - npm test
before_script:
  - npm install codeclimate-test-reporter nyc -g
after_script:
- npm run coverage
- codeclimate-test-reporter < ./coverage/lcov.info